import pandas as pd
import pathlib
import numpy as np
from typing import Union, Tuple
import matplotlib.pyplot as plt

class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """
    
    def __init__(self, data_fname: Union[pathlib.Path, str]):
        self.data = pd.DataFrame()
        if pathlib.Path(data_fname).is_file():
            self.data_fname = pathlib.Path(data_fname)
        else:
            raise ValueError('Not a file!')


    def read_data(self):
        """
        Reads the json data located in self.data_fname into memory, to
        the attribute self.data.
        """

        self.data = pd.read_json(self.data_fname)

    def show_age_distrib(self) -> Tuple[np.ndarray, np.ndarray]:
        """
        Calculates and plots the age distribution of the participants.
        Returns a tuple containing two numpy arrays:
        The first item being the number of people in a given bin.
        The second item being the bin edges.
        """
        bins = np.linspace(0,100,11)
        histres = plt.hist(self.data['age'], bins=bins, color='skyblue', ec='black')
        plt.show()
        return histres

    def remove_rows_without_mail(self) -> pd.DataFrame:
        """
        Checks self.data for rows with invalid emails, and removes them.
        Returns the corrected DataFrame, i.e. the same table but with
        the erroneous rows removed and the (ordinal) index after a reset.
        """
        df = self.data[self.data['email'].str.contains('@[a-zA-Z]+.c')]
        df.reset_index(inplace=True, drop=True)
        return df

    def fill_na_with_mean(self) -> Union[pd.DataFrame, np.ndarray]:
        """
        Finds, in the original DataFrame, the subjects that didn't answer
        all questions, and replaces that missing value with the mean of the
        other grades for that student. Returns the corrected DataFrame,
        as well as the row indices of the students that their new grades
        were generated.
        """

        grade_info = self.data.loc[:, 'q1':'q5']
        rows_with_nans = grade_info.isna().any(axis=1)
        na_grade_info = grade_info[rows_with_nans]
        na_grade_info.fillna(na_grade_info.mean())
        return na_grade_info, np.where(rows_with_nans)[0]

    def correlate_gender_age(self) -> pd.DataFrame:
        """
        Looks for a correlation between the gender of the subject, their age
        and the score for all five questions.
        Returns a DataFrame with a MultiIndex containing the gender and whether
        the subject is above 40 years of age, and the average score in each of
        the five questions.
        """
        df = self.data
        df.set_index(['gender', 'age'], append=True)
        df['OlderThan40'] = self.data['age'] > 40
        return df.groupby(['gender', 'OlderThan40']).mean()


if __name__ == '__main__':
    file_name = pathlib.Path('data.json')
    qa = QuestionnaireAnalysis(file_name)
    qa.read_data()
    print(qa)
